import { test, expect } from '@playwright/test'
import { startNewGame } from './helpers.js'

test('国内市场和股票支持完整买卖', async ({ page }) => {
  await startNewGame(page, { name: '交易测试' })

  const marketRow = page.locator('[data-testid^="market-buy-row-"]').first()
  const itemName = (await marketRow.locator('.product-name').innerText()).trim()
  await marketRow.getByRole('button', { name: '购买' }).click()

  await expect(page.getByTestId('trade-dialog')).toBeVisible()
  await page.getByTestId('trade-quantity').locator('input').fill('2')
  await page.getByTestId('trade-confirm').click()
  await expect(page.getByText(`已购买 2 个${itemName}`, { exact: true })).toBeVisible()

  const ownedRow = page.locator('[data-testid^="market-owned-row-"]').filter({ hasText: itemName })
  await expect(ownedRow).toContainText('2')
  await ownedRow.getByRole('button', { name: '出售' }).click()
  await page.getByTestId('trade-quantity').locator('input').fill('1')
  await page.getByTestId('trade-confirm').click()
  await expect(page.getByText(new RegExp(`已出售 1 个${itemName}`))).toBeVisible()
  await expect(ownedRow).toContainText('1')

  await page.getByTestId('menu-stock').click()
  await expect(page.getByTestId('page-stock')).toBeVisible()
  await page.getByTestId('stock-amount').locator('input').fill('10')
  await page.getByTestId('stock-buy').click()
  await expect(page.getByTestId('stock-holding')).toHaveText('10 股')
  await page.getByTestId('stock-sell').click()
  await expect(page.getByTestId('stock-holding')).toHaveText('0 股')
})

test('银行支持存款、取款、贷款和一次性还款', async ({ page }) => {
  await startNewGame(page, { name: '银行测试' })
  await page.getByTestId('menu-bank').click()
  await expect(page.getByTestId('page-bank')).toBeVisible()

  await page.getByTestId('bank-deposit-amount').locator('input').fill('1000')
  await page.getByTestId('bank-deposit').click()
  await expect(page.getByText('已存款 1000 元', { exact: true })).toBeVisible()
  await expect(page.getByTestId('bank-balance')).toHaveText('1 千')

  await page.getByTestId('bank-withdraw-amount').locator('input').fill('100')
  await page.getByTestId('bank-withdraw').click()
  await expect(page.getByText('已取款 100 元', { exact: true })).toBeVisible()
  await expect(page.getByTestId('bank-balance')).toHaveText('900 元')

  await page.getByTestId('bank-loan-amount').locator('input').fill('100')
  await page.getByTestId('bank-loan').click()
  await expect(page.getByTestId('bank-loan-balance')).toHaveText('100 元')
  await expect(page.getByTestId('bank-repay')).toBeVisible()

  await page.getByTestId('bank-repay').click()
  const confirmation = page.locator('.el-message-box')
  await expect(confirmation).toContainText('偿还贷款确认')
  await confirmation.getByRole('button', { name: '确认还款' }).click()
  await expect(page.getByTestId('bank-loan-balance')).toHaveText('0 元')
  await expect(page.getByText(/贷款已全部还清/)).toBeVisible()
})

test('房产和车辆支持购买后出售', async ({ page }) => {
  await startNewGame(page, { name: '资产测试' })

  await page.getByTestId('menu-realestate').click()
  await expect(page.getByTestId('page-realestate')).toBeVisible()
  const buyHouse = page.locator('button[data-testid^="buy-house-"]:not([disabled])').first()
  const houseId = (await buyHouse.getAttribute('data-testid')).replace('buy-house-', '')
  const houseCard = page.getByTestId(`house-${houseId}`)
  const houseName = (await houseCard.locator('.property-name').first().innerText()).trim()
  await buyHouse.click()
  await expect(page.getByText(`成功购买 ${houseName}！`, { exact: true })).toBeVisible()
  const houseMoment = page.getByTestId('asset-purchase-moment')
  await expect(houseMoment).toBeVisible()
  await expect(houseMoment).toContainText('属于你的新生活正式启程')
  await expect(houseMoment).toContainText(houseName)
  await expect(houseMoment.getByTestId('asset-purchase-stage')).toHaveClass(/purchase-house/)
  await expect(houseMoment.getByTestId('asset-purchase-sequence').locator('.purchase-beat')).toHaveCount(3)
  await expect.poll(() => houseMoment.locator('.purchase-backdrop').evaluate(image => image.naturalWidth)).toBeGreaterThan(0)
  await expect(houseMoment.getByTestId('asset-purchase-item')).toHaveAttribute('src', /\/images\/houseinfo\/houses\/.+\.webp/)
  await expect.poll(() => houseMoment.getByTestId('asset-purchase-item').evaluate(image => image.naturalWidth)).toBeGreaterThan(0)
  await houseMoment.getByTestId('close-purchase-moment').click()
  await expect(houseMoment).toBeHidden()
  await expect(page.getByTestId(`owned-house-${houseId}`)).toBeVisible()
  await expect(page.getByTestId(`owned-house-image-${houseId}`)).toBeVisible()
  await expect(page.getByTestId(`owned-house-image-${houseId}`).locator('img')).toHaveAttribute('src', /\/images\/houseinfo\/houses\/.+\.webp/)
  await expect.poll(() => page.getByTestId(`owned-house-image-${houseId}`).locator('img').evaluate(image => image.naturalWidth)).toBeGreaterThan(0)
  await page.getByTestId(`owned-house-image-${houseId}`).click()
  const housePreview = page.locator('[data-testid="asset-purchase-moment"]:visible')
  await expect(housePreview).toContainText('在交付现场预览这处理想住所')
  await expect(housePreview.getByTestId('asset-purchase-stage')).toHaveClass(/asset-showcase-stage/)
  await expect(housePreview.getByTestId('asset-showcase-specs')).toBeVisible()
  await expect(housePreview.getByTestId('asset-ownership-status')).toHaveText('已购买')
  await housePreview.getByTestId('close-purchase-moment').click()
  await page.getByTestId(`sell-house-${houseId}`).click()
  await expect(page.getByTestId(`owned-house-${houseId}`)).toBeHidden()

  await page.getByTestId('menu-carshop').click()
  await expect(page.getByTestId('page-carshop')).toBeVisible()
  const buyCar = page.locator('button[data-testid^="buy-car-"]:not([disabled])').first()
  const carId = (await buyCar.getAttribute('data-testid')).replace('buy-car-', '')
  const carCard = page.getByTestId(`car-${carId}`)
  const carName = (await carCard.locator('.property-name').first().innerText()).trim()
  await buyCar.click()
  await expect(page.getByText(`成功购买 ${carName}！`, { exact: true })).toBeVisible()
  const carMoment = page.getByTestId('asset-purchase-moment')
  await expect(carMoment).toBeVisible()
  await expect(carMoment).toContainText('属于你的新座驾正式交付')
  await expect(carMoment).toContainText(carName)
  await expect(carMoment.getByTestId('asset-purchase-stage')).toHaveClass(/purchase-car/)
  await expect(carMoment.getByTestId('asset-purchase-sequence').locator('.purchase-beat')).toHaveCount(3)
  await expect.poll(() => carMoment.locator('.purchase-backdrop').evaluate(image => image.naturalWidth)).toBeGreaterThan(0)
  await expect(carMoment.getByTestId('asset-purchase-item')).toHaveAttribute('src', /\/images\/carinfo\/cars\/.+\.webp/)
  await expect.poll(() => carMoment.getByTestId('asset-purchase-item').evaluate(image => image.naturalWidth)).toBeGreaterThan(0)
  await carMoment.getByTestId('close-purchase-moment').click()
  await expect(carMoment).toBeHidden()
  await expect(page.getByTestId(`owned-car-${carId}`)).toBeVisible()
  await expect(page.getByTestId(`owned-car-image-${carId}`)).toBeVisible()
  await expect(page.getByTestId(`owned-car-image-${carId}`).locator('img')).toHaveAttribute('src', /\/images\/carinfo\/cars\/.+\.webp/)
  await expect.poll(() => page.getByTestId(`owned-car-image-${carId}`).locator('img').evaluate(image => image.naturalWidth)).toBeGreaterThan(0)
  await page.getByTestId(`owned-car-image-${carId}`).click()
  const carPreview = page.locator('[data-testid="asset-purchase-moment"]:visible')
  await expect(carPreview).toContainText('在私人展厅里鉴赏这台座驾')
  await expect(carPreview.getByTestId('asset-purchase-stage')).toHaveClass(/asset-showcase-stage/)
  await expect(carPreview.getByTestId('asset-showcase-specs')).toBeVisible()
  await expect(carPreview.getByTestId('asset-ownership-status')).toHaveText('已购买')
  await carPreview.getByTestId('close-purchase-moment').click()
  await page.getByTestId(`sell-car-${carId}`).click()
  await expect(page.getByTestId(`owned-car-${carId}`)).toBeHidden()
})

test('医院、娱乐活动和存档删除流程可用', async ({ page }) => {
  await startNewGame(page, { name: '服务测试' })

  await page.getByTestId('menu-hospital').click()
  await expect(page.getByTestId('page-hospital')).toBeVisible()
  await page.getByTestId('hospital-pharmacy').click()
  await page.getByTestId('hospital-service-1').click()
  const medicine = page.locator('[data-testid^="medicine-"]').first()
  await expect(medicine).toBeVisible()
  await medicine.click()
  await expect(page.getByText('购买成功！', { exact: true })).toBeVisible()

  await page.getByTestId('menu-entertainment').click()
  await expect(page.getByTestId('page-entertainment')).toBeVisible()
  await page.getByTestId('entertainment-activity-film').click()
  await expect(page.getByTestId('activity-confirm-dialog')).toBeVisible()
  await page.getByTestId('confirm-activity').click()
  await expect(page.getByText(/参与成功/)).toBeVisible()

  await page.getByTestId('open-save-dialog').click()
  await page.getByPlaceholder('输入存档名称').fill('待删除存档')
  await page.getByTestId('create-save').click()
  const saveRow = page.locator('.save-item').filter({ hasText: '待删除存档' })
  await expect(saveRow).toBeVisible()
  await saveRow.getByRole('button', { name: '删除' }).click()
  const deleteConfirmation = page.locator('.el-message-box')
  await deleteConfirmation.getByRole('button', { name: '删除', exact: true }).click()
  await expect(page.getByText('删除成功', { exact: true })).toBeVisible()
  await expect(saveRow).toBeHidden()
})
