// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddMiniGameWager(arg1) {
  return window['go']['services']['App']['AddMiniGameWager'](arg1);
}

export function ApplyLoan(arg1) {
  return window['go']['services']['App']['ApplyLoan'](arg1);
}

export function AuctionEnd(arg1, arg2) {
  return window['go']['services']['App']['AuctionEnd'](arg1, arg2);
}

export function BatheWithSpouse(arg1) {
  return window['go']['services']['App']['BatheWithSpouse'](arg1);
}

export function BreakUpDating(arg1) {
  return window['go']['services']['App']['BreakUpDating'](arg1);
}

export function BuyCar(arg1) {
  return window['go']['services']['App']['BuyCar'](arg1);
}

export function BuyHouse(arg1) {
  return window['go']['services']['App']['BuyHouse'](arg1);
}

export function BuyItem(arg1, arg2, arg3) {
  return window['go']['services']['App']['BuyItem'](arg1, arg2, arg3);
}

export function BuyTreatment(arg1, arg2) {
  return window['go']['services']['App']['BuyTreatment'](arg1, arg2);
}

export function CancelMiniGame(arg1) {
  return window['go']['services']['App']['CancelMiniGame'](arg1);
}

export function ClaimTaskReward(arg1) {
  return window['go']['services']['App']['ClaimTaskReward'](arg1);
}

export function DeleteSave(arg1) {
  return window['go']['services']['App']['DeleteSave'](arg1);
}

export function DivorceDating(arg1) {
  return window['go']['services']['App']['DivorceDating'](arg1);
}

export function DoDating(arg1, arg2) {
  return window['go']['services']['App']['DoDating'](arg1, arg2);
}

export function DoDatingInteraction(arg1, arg2, arg3) {
  return window['go']['services']['App']['DoDatingInteraction'](arg1, arg2, arg3);
}

export function DoEntertainment(arg1) {
  return window['go']['services']['App']['DoEntertainment'](arg1);
}

export function EmergencyTreatment() {
  return window['go']['services']['App']['EmergencyTreatment']();
}

export function EndGame() {
  return window['go']['services']['App']['EndGame']();
}

export function EndMiniGame(arg1) {
  return window['go']['services']['App']['EndMiniGame'](arg1);
}

export function GetAntique(arg1) {
  return window['go']['services']['App']['GetAntique'](arg1);
}

export function GetBankTaskList() {
  return window['go']['services']['App']['GetBankTaskList']();
}

export function GetDatingGiftOptions(arg1) {
  return window['go']['services']['App']['GetDatingGiftOptions'](arg1);
}

export function GetDatingInfo() {
  return window['go']['services']['App']['GetDatingInfo']();
}

export function GetEntertainmentActivities() {
  return window['go']['services']['App']['GetEntertainmentActivities']();
}

export function GetHospitalInfo() {
  return window['go']['services']['App']['GetHospitalInfo']();
}

export function GetMiniGameConfigs() {
  return window['go']['services']['App']['GetMiniGameConfigs']();
}

export function GetStartupStatus() {
  return window['go']['services']['App']['GetStartupStatus']();
}

export function GiveDatingGift(arg1, arg2) {
  return window['go']['services']['App']['GiveDatingGift'](arg1, arg2);
}

export function InitGame(arg1, arg2, arg3) {
  return window['go']['services']['App']['InitGame'](arg1, arg2, arg3);
}

export function ListSaves() {
  return window['go']['services']['App']['ListSaves']();
}

export function LoadGame(arg1) {
  return window['go']['services']['App']['LoadGame'](arg1);
}

export function MarryDating(arg1) {
  return window['go']['services']['App']['MarryDating'](arg1);
}

export function MiniGameAction(arg1) {
  return window['go']['services']['App']['MiniGameAction'](arg1);
}

export function NextTime() {
  return window['go']['services']['App']['NextTime']();
}

export function OperationAntique(arg1, arg2) {
  return window['go']['services']['App']['OperationAntique'](arg1, arg2);
}

export function OperationMoney(arg1, arg2) {
  return window['go']['services']['App']['OperationMoney'](arg1, arg2);
}

export function RepayLoan(arg1) {
  return window['go']['services']['App']['RepayLoan'](arg1);
}

export function RetryStartup() {
  return window['go']['services']['App']['RetryStartup']();
}

export function SaveGame(arg1) {
  return window['go']['services']['App']['SaveGame'](arg1);
}

export function SellCar(arg1) {
  return window['go']['services']['App']['SellCar'](arg1);
}

export function SellHouse(arg1) {
  return window['go']['services']['App']['SellHouse'](arg1);
}

export function SellItem(arg1, arg2, arg3) {
  return window['go']['services']['App']['SellItem'](arg1, arg2, arg3);
}

export function SpecialTreatment(arg1, arg2) {
  return window['go']['services']['App']['SpecialTreatment'](arg1, arg2);
}

export function StartMiniGame(arg1, arg2) {
  return window['go']['services']['App']['StartMiniGame'](arg1, arg2);
}

export function StartMiniGameWithOptions(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['services']['App']['StartMiniGameWithOptions'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdateStock() {
  return window['go']['services']['App']['UpdateStock']();
}

export function VisitDatingScene(arg1) {
  return window['go']['services']['App']['VisitDatingScene'](arg1);
}
