// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function AddMiniGameWager(arg1:number):Promise<services.H>;

export function ApplyLoan(arg1:number):Promise<services.H>;

export function AuctionEnd(arg1:number,arg2:number):Promise<services.H>;

export function BatheWithSpouse(arg1:number):Promise<services.SpouseInteractionResponse>;

export function BreakUpDating(arg1:number):Promise<services.DatingRelationshipResponse>;

export function BuyCar(arg1:number):Promise<services.H>;

export function BuyHouse(arg1:number):Promise<services.H>;

export function BuyItem(arg1:number,arg2:number,arg3:string):Promise<services.H>;

export function BuyTreatment(arg1:string,arg2:number):Promise<services.H>;

export function CancelMiniGame(arg1:string):Promise<services.H>;

export function ClaimTaskReward(arg1:number):Promise<services.H>;

export function DeleteSave(arg1:number):Promise<services.BasicResponse>;

export function DivorceDating(arg1:number):Promise<services.DatingRelationshipResponse>;

export function DoDating(arg1:number,arg2:string):Promise<services.DatingResultResponse>;

export function DoDatingInteraction(arg1:number,arg2:string,arg3:string):Promise<services.DatingInteractionResponse>;

export function DoEntertainment(arg1:string):Promise<services.H>;

export function EmergencyTreatment():Promise<services.H>;

export function EndGame():Promise<services.EvaluationResponse>;

export function EndMiniGame(arg1:number):Promise<services.H>;

export function GetAntique(arg1:number):Promise<services.H>;

export function GetBankTaskList():Promise<services.H>;

export function GetDatingGiftOptions(arg1:number):Promise<services.DatingGiftOptionsResponse>;

export function GetDatingInfo():Promise<services.DatingListResponse>;

export function GetEntertainmentActivities():Promise<services.H>;

export function GetHospitalInfo():Promise<services.H>;

export function GetMiniGameConfigs():Promise<services.H>;

export function GetStartupStatus():Promise<services.StartupResponse>;

export function GiveDatingGift(arg1:number,arg2:string):Promise<services.DatingRelationshipResponse>;

export function InitGame(arg1:string,arg2:boolean,arg3:number):Promise<services.GameStateResponse>;

export function ListSaves():Promise<services.ListSavesResponse>;

export function LoadGame(arg1:number):Promise<services.LoadGameResponse>;

export function MarryDating(arg1:number):Promise<services.DatingRelationshipResponse>;

export function MiniGameAction(arg1:string):Promise<services.H>;

export function NextTime():Promise<services.GameStateResponse>;

export function OperationAntique(arg1:number,arg2:number):Promise<services.H>;

export function OperationMoney(arg1:string,arg2:number):Promise<services.H>;

export function RepayLoan(arg1:number):Promise<services.H>;

export function RetryStartup():Promise<services.StartupResponse>;

export function SaveGame(arg1:string):Promise<services.SaveGameResponse>;

export function SellCar(arg1:number):Promise<services.H>;

export function SellHouse(arg1:number):Promise<services.H>;

export function SellItem(arg1:number,arg2:number,arg3:string):Promise<services.H>;

export function SpecialTreatment(arg1:string,arg2:string):Promise<services.H>;

export function StartMiniGame(arg1:string,arg2:number):Promise<services.H>;

export function StartMiniGameWithOptions(arg1:string,arg2:number,arg3:number,arg4:string,arg5:number):Promise<services.H>;

export function UpdateStock():Promise<services.StockUpdateResponse>;

export function VisitDatingScene(arg1:string):Promise<services.DatingSceneResponse>;
